[package]
name = "lily"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-only"
keywords = ["cli", "quotes"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"